export const typesMethodAccount = Object.freeze({
    BAN: "ban",
    CHANGE_PASSWORD: "changePassword",
    GET_ACTIVE_OFFERS: "getActiveOffers",
    GET_APP_PERMISSIONS: "getAppPermissions",
    GET_BANNED: "getBanned",
    GET_COUNTERS: "getCounters",
    GET_INFO: "getInfo",
    GET_PROFILE_INFO: "getProfileInfo",
    GET_PUSH_SETTINGS: "getPushSettings",
    LOOKUP_CONTACTS: "lookupContacts",
    REGISTER_DEVICE: "registerDevice",
    SAVE_PROFILE_INFO: "saveProfileInfo",
    SET_INFO: "setInfo",
    SET_NAME_IN_MENU: "setNameInMenu",
    SET_OFFLINE: "setOffline",
    SET_ONLINE: "setOnline",
    SET_PUSH_SETTINGS: "setPushSettings",
    SET_SILENCE_MODE: "setSilenceMode",
    UNBAN: "unban",
    UNREGISTER_DEVICE: "unregisterDevice"
});