export const METHOD_API_ERROR_CODE = {
    UNKNOWN_METHOD: 3,
    INVALID_SIGNATURE: 4,

    CAPTCHA_NEEDED: 14,
    VALIDATION_REQUIRED: 17,
    CONFIRMATION_REQUIRED: 24,

    INVALID_RESPONSE: 1001,
    INIT_LONG_POOL_SERVER: 1050,
    UPDATE_LONG_POOL_SERVER: 1051
}